[PyTorch](https://pytorch.org/)


## PyTorch Fundamentals

### Table of Contents
1. [Introduction to Tensors](#tensors)
2. [Random Tensors](#randomtensors)
3. [Creating Tensors with zeros and ones in PyTorch](#zeros&ones)
4. [Create a range of tensors and tensor-like](#range)
5. [Tensor Datatypes](#datatypes)
6. [Getting tensor attributes (information about tensor)](#attributes)
7. [Manipulating Tensors (Tensor Operations)](#operations)
8. [Matrix Multiplication](#matrix)
9. [Handling errors in deep learning](#errors)
10. [Tensor Aggregation](#aggregate)
11. [Reshaping, stacking, squeezing and unsqueezing tensors](#squeeze)
12. [Indexing in Tensors](#index)
13. [Pytorch Tensors and Numpy](#numpy)
14. [PyTorch Reproducability](#reproduce)
15. [Different ways of accessing GPU in Pytorch](#gpu)
16. [Exercises and Extra Curriculum](#extras)

In [1]:
print("Hello are you excited to learn Python?")

Hello are you excited to learn Python?


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


## Introduction to Tensors  <a class='anchor' id ='tensors'>
### Creating Tensors
Pytorch Tensors are created using torch.Tensor()
![Tensor1](Tensor1.png)

In [3]:
# scalar : a single number
# torch.Tensor is a multi dimensional matrix containing elements of a single data type.
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Get tensor back as Python int
scalar.ndim # has no dimensions

0

In [5]:
# Vector : a number with direction
vector = torch.Tensor([7,7])
vector # A vector has magnitude and direction.

tensor([7., 7.])

In [6]:
vector.ndim # Has 1 dimension (no of pairs of square brackets)

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])

In [9]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape # we have got 1 3 by 3 tensor

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random Tensors <a class='anchor' id ='randomtensors'>


### Why Random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data.
* `Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`




In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7443, 0.8337, 0.2419, 0.3189],
        [0.7135, 0.0553, 0.6950, 0.8438],
        [0.2054, 0.5015, 0.0119, 0.1585]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[0.3046, 0.2038, 0.6722, 0.5779, 0.3877, 0.8391, 0.9169, 0.5119,
          0.2738, 0.5565],
         [0.8323, 0.1107, 0.9420, 0.1152, 0.8877, 0.9705, 0.3609, 0.8665,
          0.3485, 0.3546],
         [0.8618, 0.6919, 0.6445, 0.9430, 0.7355, 0.1839, 0.9702, 0.5325,
          0.0494, 0.3887],
         [0.8572, 0.1194, 0.5885, 0.2815, 0.6563, 0.7858, 0.0934, 0.3367,
          0.9181, 0.5195],
         [0.1227, 0.7328, 0.6347, 0.6548, 0.8020, 0.0323, 0.4476, 0.2638,
          0.2967, 0.7529],
         [0.8631, 0.1978, 0.8885, 0.4663, 0.9428, 0.0395, 0.2507, 0.9113,
          0.3272, 0.0271],
         [0.6992, 0.3616, 0.6618, 0.7714, 0.8997, 0.1916, 0.7260, 0.2270,
          0.9826, 0.0285],
         [0.5461, 0.2082, 0.1339, 0.7378, 0.6581, 0.6736, 0.4026, 0.3458,
          0.7269, 0.6030],
         [0.1923, 0.6106, 0.1811, 0.3279, 0.9925, 0.5573, 0.8240, 0.3023,
          0.8517, 0.4096],
         [0.6394, 0.5688, 0.7574, 0.3181, 0.0089, 0.5075, 0.3965, 0.4649,
          0.7821,

In [20]:
random_tensor.ndim

3

![Tensor2](Tensor2.png)

In [22]:
# Almost any data can be represented in the form of tensor
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width,colour channels (R,G,B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Creating Tensors with zeros and ones in PyTorch <a class='anchor' id ='zeros&ones'>


In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
random_tensor.dtype

torch.float32

### Creating a  range of tensors and tensors-like <a class='anchor' id ='range'>


In [32]:
# Use torch.range(), getting depricated message use tensor.arange() instead
zero_to_ten = torch.range(0,10)
zero_to_ten

/var/folders/cy/hd9k90656lx_zrdft5_wmllh0000gn/T/ipykernel_38728/3841350212.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
zero_to_th = torch.range(start=0,end=1000,step=100)
zero_to_th

/var/folders/cy/hd9k90656lx_zrdft5_wmllh0000gn/T/ipykernel_38728/3326760929.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_th = torch.range(start=0,end=1000,step=100)


tensor([   0.,  100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,  900.,
        1000.])

In [36]:
# Creating tensors like
eleven_zeros = torch.zeros_like(input=zero_to_ten)
eleven_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor DataTypes <a class='anchor' id ='datatypes'>

* Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning :
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [43]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                              device="cpu", # what device is your tensor on
                              requires_grad=False) # whether or not to track gradients with this tensors operations

tensor([3., 6., 9.])

In [40]:
float_32_tensor.dtype

torch.float32

In [44]:
# Converting float_32_tensor into float_16_tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting tensor attributes (information about tensors)

In [47]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [48]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [52]:
long_tensor = torch.tensor([3,6,9],dtype=torch.long)
long_tensor

tensor([3, 6, 9])

In [53]:
float_32_tensor * long_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes) <a class='anchor' id ='attributes'>

1. Tensors not right datatype : to do get 'dtype' from a tensor, can use 'tensor.dtype'
2. Tensors not right shape : to get shape from a tensor, can use 'tensor.shape'
3. Tensor not on the right device : to get device from a tensor, can use 'tensor.device'

In [54]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3922, 0.9000, 0.9709, 0.1677],
        [0.0366, 0.5103, 0.9506, 0.8595],
        [0.9257, 0.9962, 0.9584, 0.1113]])

In [58]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [59]:
some_tensor.size()

torch.Size([3, 4])

In [62]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3922, 0.9000, 0.9709, 0.1677],
        [0.0366, 0.5103, 0.9506, 0.8595],
        [0.9257, 0.9962, 0.9584, 0.1113]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations) <a class='anchor' id ='operations'>


Tensor operations include :
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [68]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [71]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [72]:
# Subtract 10
tensor = tensor - 10
tensor

tensor([ 0, 10, 20])

In [73]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([  0, 100, 200])

In [74]:
torch.add(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication ( Part-1) <a class='anchor' id ='matrix'>

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix Multiplication (Dot Product)

There are 2 rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [90]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.6382, 0.5560, 0.6512],
        [0.8789, 0.4067, 0.9819],
        [0.5890, 0.4912, 0.6062]])

In [77]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")


tensor([ 0, 10, 20]) * tensor([ 0, 10, 20])
Equals:tensor([  0, 100, 400])


In [88]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(500)

In [79]:
tensor

tensor([ 0, 10, 20])

In [80]:
# Matrix Multiplication by hand
0*0 + 10*10 + 20*20 

500

In [84]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 934 µs, sys: 1.94 ms, total: 2.87 ms
Wall time: 2.51 ms


tensor(500)

In [85]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 196 µs, sys: 116 µs, total: 312 µs
Wall time: 263 µs


tensor(500)

In [86]:
tensor @ tensor

tensor(500)

### One of the most common errors in deep learning : shape errors <a class='anchor' id ='errors'>


In [96]:
# Shapes for Matrix Multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

# torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

1. To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
* A **transpose** switches he axes or dimensions of a given tensor

In [97]:
# Transpose of Tensor_B
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [100]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [105]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape:tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shape:tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min,max, mean and sum of tensors (tensor aggregation) <a class='anchor' id ='aggregate'>


In [110]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [107]:
# Find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [108]:
# Find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [115]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [116]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max of tensors

In [117]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [118]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs 
x.argmin()

tensor(0)

In [119]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors <a class='anchor' id ='squeeze'>

* Reshaping : Reshapes an input tensor to a defined shape
* View : Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking : Combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [120]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [123]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [124]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [125]:
# Change the view (shares the memory with the original tensor)
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [126]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [129]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [135]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor : {x_reshaped} ")
print(f"Previous shape  : {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped 
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor : tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) 
Previous shape  : torch.Size([9, 1])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [132]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [133]:
x_reshaped.squeeze().shape

torch.Size([9])

In [139]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor :{x_unsqueezed}")

print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor :tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [146]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224,224,3)) # [height,width,colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}") # [colour channels , height, width]

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [151]:
x_original[0,0,0]

tensor(0.7459)

### Indexing (selecting data from tensors) <a class='anchor' id ='index'>

Indexing with PyTorch is similar to indexing with NumPy

In [152]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [153]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [154]:
# Let's index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [155]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0] # 0th tensor 0th index 0th element

tensor(1)

In [159]:
x[0][0][1], x[0][1][1], x[0][2][2] # (we have only one tensor `0`)

(tensor(2), tensor(5), tensor(9))

In [160]:
# You can also use ":" to select "all" of a target dimension
x[:,0] # select all of 0th dimension

tensor([[1, 2, 3]])

In [166]:
# Get all values of 0th and 1st dimension but only 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [167]:
# Get all values of 0 dimension but only 1index of 1st & 2nd dimension
x[:,1,1]

tensor([5])

In [168]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [177]:
# Index on x to return 9
print(x[0,2,2])

# Index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


### PyTorch tensors & NumPy <a class='anchor' id ='numpy'>

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to intercat with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [182]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
# warning: when converting from numpy -> pytorch,pytorch reflects numpy's default datatype of float64 unless specified otherwise

tensor = torch.from_numpy(array).type(torch.float32) # Changing the default datatype
array, tensor # tensor default datatype if float64

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [179]:
array.dtype

dtype('float64')

In [180]:
tensor.dtype

torch.float64

In [181]:
torch.arange(1.0,8.0).dtype

torch.float32

In [184]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor # it doesn't change the value of tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [186]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [187]:
numpy_tensor.dtype

dtype('float32')

In [188]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### PyTorch Reproducability (taking the random out of random) <a class='anchor' id ='reproduce'>


In short how a neural network learns:

`start with random numbers -> tensor operations -> update random number to try and make them better representations of the data -> again -> again -> again ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [189]:
torch.rand(3,3)

tensor([[0.6705, 0.9907, 0.6989],
        [0.5619, 0.7989, 0.6296],
        [0.0635, 0.5595, 0.9283]])

In [190]:
import torch
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.6758, 0.1030, 0.5648, 0.8088],
        [0.8536, 0.6221, 0.6175, 0.0847],
        [0.6253, 0.2150, 0.0648, 0.1920]])
tensor([[0.4178, 0.1871, 0.8134, 0.7154],
        [0.6402, 0.2690, 0.5644, 0.9584],
        [0.0500, 0.1678, 0.6741, 0.3646]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [192]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Different ways of accessing a GPU in PyTorch <a class='anchor' id ='gpu'>


Running tensors and PyTorch objects on the GPU's (and making faster computations)
GPUs = faster computation on numbers, `CUDA + NVIDIA hardware + PyTorch`

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well).
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure


### Check for GPU access with PyTorch

In [193]:
# Check for a GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For Pytorch since it's capable of running compute on the GPU, it's best practice to setup device agnostic code. E.g : run on GPU if available, else default to CPU

In [194]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [195]:
# Count number of devices
torch.cuda.device_count()

0

### Setting up device agnostic code and putting tensors on and off the GPU

Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [197]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [198]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

#### Moving tensors back to the CPU


In [199]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy() # here tensor is on CPU

array([1, 2, 3])

In [201]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### Exercises and Extra- curriculum <a class='anchor' id ='extras'>


#### 2. Create a random tensor with shape `(7,7)`

In [224]:
tensor_1 = torch.rand(7,7)
tensor_1, tensor_1.shape

(tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071],
         [0.6297, 0.3653, 0.8513, 0.8549, 0.5509, 0.2868, 0.2063],
         [0.4451, 0.3593, 0.7204, 0.0731, 0.9699, 0.1078, 0.8829],
         [0.4132, 0.7572, 0.6948, 0.5209, 0.5932, 0.8797, 0.6286],
         [0.7653, 0.1132, 0.8559, 0.6721, 0.6267, 0.5691, 0.7437],
         [0.9592, 0.3887, 0.2214, 0.3742, 0.1953, 0.7405, 0.2529],
         [0.2332, 0.9314, 0.9575, 0.5575, 0.4134, 0.4355, 0.7369]]),
 torch.Size([7, 7]))

#### 3. Perform a matrix multiplication on the tensor from `2` with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).


In [206]:
tensor_2 = torch.rand(1,7)
torch.matmul(tensor_1,tensor_2.T)

tensor([[1.4402],
        [1.4841],
        [1.4790],
        [1.1776],
        [0.5887],
        [1.3285],
        [0.8125]])

#### 4. Set the random seed to 0 and do exercises 2 & 3 over again.


In [208]:
RANDOM_SEED = 99
torch.manual_seed(RANDOM_SEED)

tensor_1 = torch.rand(7,7)
tensor_2 = torch.rand(1,7)

torch.matmul(tensor_1,tensor_2.T)

tensor([[3.7643],
        [2.4132],
        [2.8977],
        [2.3246],
        [2.3044],
        [2.1474],
        [2.7186]])

#### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [225]:
# Setting random seed on GPU
torch.manual_seed(1234)

#### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).


In [226]:
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)
tensor_A_on_gpu = tensor_A.to(device)
tensor_B_on_gpu = tensor_B.to(device)

#### 7. Find the maximum and minimum values of the output of 7.

In [212]:
tensor_A_cpu = tensor_A_on_gpu.cpu()
tensor_B_cpu = tensor_B_on_gpu.cpu()
output = torch.matmul(tensor_A_cpu,tensor_B_cpu.T)
output

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

#### 8. Find the maximum and minimum values of the output of 7.

In [214]:
torch.min(output), torch.max(output)

(tensor(0.3647), tensor(0.5617))

#### 9.Find the maximum and minimum index values of the output of 7.

In [215]:
output.argmin(), output.argmax()

(tensor(0), tensor(3))

#### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [227]:
torch.manual_seed(7)

tensor_C = torch.rand(1,1,1,10)
tensor_D = tensor_C.squeeze()

print(tensor_C, tensor_C.shape)
print(tensor_D, tensor_D.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
